server:
  port: 2003

spring:
  application:
    name: seata-account-service
#  cloud:
#    alibaba:
#      seata:
#        tx-service-group: default
#    nacos:
#      discovery:
#        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_account?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false
    username: root
    password: zz936127241

seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: my_test_tx_group
  enable-auto-data-source-proxy: false
  service:
    vgroup-mapping:
      my_test_tx_group: default
    grouplist:
      default: 127.0.0.1:8091
    enable-degrade: false
    disable-global-transaction: false
  config:
    type: nacos
    nacos:
      namespace: ac26d165-a05b-4fb2-a2b4-fdb727942e68
      serverAddr: 127.0.0.1:8848
      group: SEATA_GROUP
      userName: nacos
      password: nacos
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      userName: nacos
      password: nacos
      cluster: default
      group: SEATA_GROUP
      namespace: ac26d165-a05b-4fb2-a2b4-fdb727942e68


feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml


